### ISSUE TITLE
[UI Bug] In blog, when we search for something, the filter options overlap with the results

### ISSUE THREAD

**Issue by AkhilParim** [topcoder-platform/Training-Challenges#136] opened 2020-05-29 19:23 UTC
**Steps to reproduce:**
1. Go to https://www.topcoder.com
2. Go to blog page
3. Search for something in the search box
4. Click on filter button

Actual result:
Filter options overlap with the results.

Expected result:
Filter options should appear on the results.

**Screenshots:**
<img width="1180" alt="Screenshot 2020-05-30 at 12 37 46 AM" src="https://user-images.githubusercontent.com/45338579/83296634-b9e11800-a20e-11ea-9dd4-253ec9ef987c.png">

**Device/OS/Browser Information:**
Safari
Apple Mac OS X 10.15.5

**Comment by nithyaasworld** [comment] 2020-05-30 17:40
@AkhilParim This is duplicate of https://github.com/topcoder-platform/Training-Challenges/issues/112

Please always search the issue-list with different keywords to make sure that the bug is not already reported.

**Closed** 2021-05-28 18:47 UTC
Labels: duplicate
