### ISSUE TITLE
UX/UI Error: Text in view more case studies box overflows when text size and spacing are at max

### ISSUE THREAD

**Issue by emerzon1** [topcoder-platform/Training-Challenges#100] opened 2020-04-19 13:23 UTC
To Reproduce:
1. Go to https://www.topcoder.com
2. Scroll down to the banner "Our customers, their success"
3. Click the accessibility button in bottom right.
4. Put text size and spacing at max values
5. Look at box that says view more case studies.
Expected: Box grows as text size and spacing grow
Actual: Text overflows making it ugly

<img width="1440" alt="Screen Shot 2020-04-19 at 9 21 36 AM" src="https://user-images.githubusercontent.com/59055006/79688866-2edc2d80-821f-11ea-8be0-4168c9f3db14.png">
Device: MacOSx MacBook Air Catalina 2020

**Comment by nithyaasworld** [comment] 2020-04-20 04:49
Please rewrite your bug by following the feedback given here: #97

**Comment by emerzon1** [comment] 2020-04-21 20:52
Fixed all of them

**Comment by nithyaasworld** [comment] 2020-04-23 06:54
Good Job @emerzon1

**Comment by nithyaasworld** [comment] 2020-04-23 07:00
Also duplicate of #85

**Closed** 2021-05-28 18:46 UTC
Labels: Accepted, duplicate
