### ISSUE TITLE
[UI Isssue]-In COMPETITION RULES page 'Stage 2' date's year is not written Correctly

### ISSUE THREAD

**Issue by ritik02797** [topcoder-platform/Training-Challenges#62] opened 2020-01-14 09:59 UTC
**Steps to Reproduce:**

1. Go To (https://www.topcoder.com/community/learn) this link.

**Comment by nithyaasworld** [comment] 2020-04-14 01:40
Closing this as its duplicate of https://github.com/topcoder-platform/Training-Challenges/issues/63

**Closed by nithyaasworld** 2020-04-14 01:40 UTC
