### ISSUE TITLE
Payment Section profile 

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/Training-Challenges#12] opened 2019-11-27 21:20 UTC
Go to : "Challenge Forum" the profile picture of the topcoder member does not reflect in the Payment section.
ACTUAL RESULT: The profile picture is not displayed.
EXPECTED RESULT: The profile picture of the member should be visible once in the challenge forum.
![payment](https://user-images.githubusercontent.com/37167721/69760158-cf4c8b00-1174-11ea-9fb8-aea6c5f4ddb3.jpg)

Device/OS/Browser Information: Linux,Ubuntu
OS: Kali
Browser information:Chromium Browser, Version 73.0.3683.75 (Developer Build) built on Debian buster/side, running on Debian kali-rolling (32-bit)

**Comment by nithyaasworld** [comment] 2019-11-28 07:30
This will be duplicate of https://github.com/topcoder-platform/Training-Challenges/issues/11 as the header is common to these two pages, it's not a good practice to report similar bugs of each page as separate bugs.

It's better to combine them as 1 or add a comment to this existing bug https://github.com/topcoder-platform/Training-Challenges/issues/11 and state about the Payment section page.

**Closed** 2021-05-28 18:48 UTC
Labels: duplicate
