### ISSUE TITLE
[UI bug] Broken image displayed for user avatar

### ISSUE THREAD

**Issue by haritaToboso** [topcoder-platform/Training-Challenges#108] opened 2020-04-28 08:01 UTC
**Steps to Reproduce:**
1. Launch [http://www.topcoder.com](url)
2. Click on "View Enterprise Offering"
3. User is navigated to [https://www.topcoder.com/enterprise-offerings/](url)

**Actual Result:**
User avatar should be displayed on top-right side.

**Expected Result:** 
Broken image is displayed in place of avatar.

**Screenshots or screencast URL:**
![image](https://user-images.githubusercontent.com/61909695/80462111-e249ce00-8953-11ea-8841-0fa868006182.png)

**Device/OS/Browser Information:**
PC-Windows-Chrome

**Additonal Informations:**

- Bug Type - UI Bug

- Priority - P3(Low)

- Chrome Version - 81.0.4044.122

**Comment by nithyaasworld** [comment] 2020-04-28 08:07
@haritaToboso Can you tell me if you have any profile pic added to your Topcoder Account?

**Comment by haritaToboso** [comment] 2020-04-28 08:11
@nithyaasworld No profile pic is added. Just my initials are displayed.

**Comment by nithyaasworld** [comment] 2020-04-28 08:15
@haritaToboso Ok, I am not able to reproduce this issue. I also checked for another account which doesn't have profile pic and its not reproducible with that account too. I am able to see the initials.

Can you check again please?

![image](https://user-images.githubusercontent.com/5114190/80463790-6c933180-8956-11ea-98ff-b7ae082b4024.png)

**Comment by haritaToboso** [comment] 2020-04-28 09:52
@nithyaasworld
 I have retested the same. Working fine now. Shall I proceed with closing  the defect?
![image](https://user-images.githubusercontent.com/61909695/80473496-d960f880-8963-11ea-8a78-d3a65c5f6b69.png)

**Comment by nithyaasworld** [comment] 2020-04-28 10:16
Yes @haritaToboso We can close this now as its not reproducible.

In reality, there may be times wherein you will be able to reproduce a bug only at certain time. In those cases, try to remember and follow the scenarios you tried just before encountering into bug, try all the possibilities to reproduce the bug and provide as much info as possible to reproduce the bug. This will enhance the possibility of our bug getting accepted.

Keep hunting! There must be some places where no has explored(tested) yet. There must be some scenarios that no one has tried yet. There must be some obvious bugs that no one has reported it yet.

**Closed** 2021-05-28 18:46 UTC
Labels: Feedback provided
